#!/usr/bin/bash

## Usar `tee`
# https://github.com/vysheng/tg/issues/863

## Gist: comandos
# https://gist.github.com/weibeld/281feed0b2f5d141fa7e85fc618dd7fc

## tg-cli arguments
# https://github.com/vysheng/tg/wiki/Telegram-CLI-Arguments#available-arguments

log_id=$1

telegram_command="telegram-cli -W -C -N --permanent-msg-ids -e"

sleep 1
msg_id=$(
  $telegram_command "msg mojinho 'getlog $log_id'" |
    tee tmp.out |
    grep "document" |
    sed -E "s/.\[K(\w+)(.*)/\1/" # por algum motivo o primeiro caractere do /SUBSTITUTION/ se perde no comando `sed`
)

sleep 1

msg_id=$(echo $msg_id | cut -c 4-) ## dispensar os 3 primeiros bytes
echo ">>      msg id: $msg_id >> msg id"
echo ">> msg id size: ${#msg_id}"

downloaded_file="olá"
downloaded_file=$(
  $telegram_command "load_document $msg_id" |
    tee tmp-download.out |
    grep "Saved to"
)

echo "downloaded file: $downloaded_file"
echo "downloaded file ^^^^^^^^^^^^^^^^"
